### ISSUE TITLE
Incorrect HTML Attribute Concatenation and Deprecated API Usage

### ISSUE THREAD

**Issue by MOACKDC** [vsys-host/whmcs-shkeeper-gateway-module#1]
## Description

There's an error in the HTML string concatenation within the provided code snippet where the `img` tag's `src` and `title` attributes are not properly separated. This results in the `title` attribute being mistakenly included within the `src` URL. Additionally, the Google QR Code API previously used is now deprecated and no longer functional.

## Original Code

```php
$html .= '<div><img src="' . $qrSrc . ' title="QR code" />';
```

## Issue Details

In the above code, the `src` attribute is not properly closed with a quotation mark (`"`), causing the `title` attribute to incorrectly become part of the `src` URL. This leads to the `title` parameter being incorrectly included in the QR code request content. This misconfiguration can result in errors during QR code generation and HTML rendering issues.

## Suggested Fix

Properly close the `src` attribute with a quotation mark before the `title` attribute begins to ensure that HTML is correctly formatted:

```php
$html .= '<div><img src="' . $qrSrc . '" title="QR code" />';
```

**Comment by Olxndr** [comment]
Hello,

Incorrect html don't cause issue with QR code generation, it's related to usage of deprecated chart.googleapis.com, but thank you, this typo will be corrected in a next commit.
As for Deprecated API Usage, WHMCS v8.9 and above includes a local QR generation library, so we will use it. For back compatibility we plan to find some another API resource for generation QR codes, maybe you know some good one? As alternative I am considering https://goqr.me/api/
